# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getChrScore_scored_k <- function(kmers, scores, chrSeq, kmerLen) {
    .Call('_fjComm_getChrScore_scored_k', PACKAGE = 'fjComm', kmers, scores, chrSeq, kmerLen)
}

getChrScore <- function(topKmers, chrSeq) {
    .Call('_fjComm_getChrScore', PACKAGE = 'fjComm', topKmers, chrSeq)
}

revComp <- function(seq) {
    .Call('_fjComm_revComp', PACKAGE = 'fjComm', seq)
}

fast_factor <- function(x) {
    .Call('_fjComm_fast_factor', PACKAGE = 'fjComm', x)
}

assign_k_to_PWMs <- function(kmers, motifs, motifNames, threshold = -1000) {
    .Call('_fjComm_assign_k_to_PWMs', PACKAGE = 'fjComm', kmers, motifs, motifNames, threshold)
}

kmerCnt <- function(strings, k = 2L, collapse = FALSE, diffLen = FALSE, asDf = FALSE) {
    .Call('_fjComm_kmerCnt', PACKAGE = 'fjComm', strings, k, collapse, diffLen, asDf)
}

kmerCnt_allgap <- function(strings, k = 2L, maxGap = 0L, asDf = TRUE, diffLen = FALSE, minGap = 0L) {
    .Call('_fjComm_kmerCnt_allgap', PACKAGE = 'fjComm', strings, k, maxGap, asDf, diffLen, minGap)
}

kmerCntBit <- function(strings, k = 2L, diffLen = FALSE, collapse = FALSE, asDf = TRUE, all_possible_k = FALSE, pseudo = 0L) {
    .Call('_fjComm_kmerCntBit', PACKAGE = 'fjComm', strings, k, diffLen, collapse, asDf, all_possible_k, pseudo)
}

gkmerCntBit <- function(strings, gapNo = 3L, k = 2L, gapMins = as.integer( c(2,3,0)), gapMaxs = as.integer( c(3,4,0)), pseudo = 0L, diffLen = FALSE, posInfo = FALSE, all_possible_k = TRUE) {
    .Call('_fjComm_gkmerCntBit', PACKAGE = 'fjComm', strings, gapNo, k, gapMins, gapMaxs, pseudo, diffLen, posInfo, all_possible_k)
}

scoring <- function(strings, scoreCube, gapNo = 3L, k = 2L, gapMins = as.integer( c(2,3,0)), gapMaxs = as.integer( c(3,4,0)), pseudo = 0L, diffLen = FALSE, posInfo = TRUE) {
    .Call('_fjComm_scoring', PACKAGE = 'fjComm', strings, scoreCube, gapNo, k, gapMins, gapMaxs, pseudo, diffLen, posInfo)
}

matRevComp <- function(seqs) {
    .Call('_fjComm_matRevComp', PACKAGE = 'fjComm', seqs)
}

pfm_from_seed_notUsed <- function(seqs, seed1 = "AAA", gapLen = 1L, seed2 = "AAA", seed1_start = as.numeric( c(2,3,4)), flankLen = 4L, all_start_with_specified_gap = TRUE) {
    .Call('_fjComm_pfm_from_seed_notUsed', PACKAGE = 'fjComm', seqs, seed1, gapLen, seed2, seed1_start, flankLen, all_start_with_specified_gap)
}

seqFregments <- function(strings, k = 2L) {
    .Call('_fjComm_seqFregments', PACKAGE = 'fjComm', strings, k)
}

